import logging

SUPPORTED_TECHNOLOGY = ['LTE', 'UMTS', 'GSM']

CUSTOMER_ID = 'CUSTOMER_ID'
SYSTEM_NAME = 'XiNOS'
PLATFORM = 'DEV' ## one of ['PRODUCTION', 'RELEASE', 'DEBUG', 'DEV']
LOGGING_LEVEL = logging.INFO\
                if PLATFORM in ['PRODUCT', 'PRODUCTION', 'RELEASE']\
                else logging.DEBUG
BLOCKSIZE = 64 * 1024
MB_TO_BYTES = 1048576
MAX_ALLOWED_PACKET = MB_TO_BYTES

TASKGROUP = 'TASKGROUP'
GSM = 'GSM'
UMTS = 'UMTS'
LTE = 'LTE'

CONF_FILE_NAME = 'etl.conf'
CONFIG_PATH = 'CONFIG_PATH'
CONFIG_FOLDER = 'CONFIG_FOLDER'
DATA_PATH = 'DATA_PATH'

DATASOURCE = 'DATASOURCE'
DSCONF_FILE_NAME = 'ds.conf'
PROTOCOL = 'PROTOCOL'
FTP = 'FTP'
SFTP = 'SFTP'
PORT = 'PORT'
USER = 'USER'
PSWD = 'PSWD'
PATH = 'PATH'
CTGR = 'CTGR'
ZIP_FLT = 'ZIP_FLT'
CSV_FLT = 'CSV_FLT'

CORE = 'CORE'
CO = 'CO'
OC = 'OC'
CM = 'CM'
DC = 'DC'
FM = 'FM'
PM = 'PM'
PCOFNSRAW = 'PCOFNSRAW'
PCOFNGRAW = 'PCOFNGRAW'
IMSCSFRAW = 'IMSCSFRAW'
IMSHSSRAW = 'IMSHSSRAW'
MADNHRRAW = 'MADNHRRAW'
MADODCRAW = 'MADODCRAW'
IMSDRARAW = 'IMSDRARAW'
XMLNSSRAW = 'XMLNSSRAW'
NOKOBWRAW = 'NOKOBWRAW'
NOKOMWRAW = 'NOKOMWRAW'
NOKIUMRAW = 'NOKIUMRAW'
DB = 'DB'

DATABASES = 'DATABASES'
DBCONF_FILE_NAME = 'db.conf'
HOST = 'HOST'
CHARSET = 'CHARSET'
TABLE = 'TABLE'

CATEGORY = 'CATEGORY'
CTP = 'CTP'
UTP = 'UTP'

DELIMITER = ';'
EOF = 'EOF'

CO_PARENT_GID = 'CO_PARENT_GID'
CSCF = 'CSCF'
DRA = 'DRA'
FINS = 'FINS'
FINS_TA = 'FINS_TA'
FING = 'FING'
HLR = 'HLR'
HSSFE = 'HSSFE'
INUMSERVER_INUMIWF = 'INUMSERVER-INUMIWF'
INUMSERVER_INUM = 'INUMSERVER-INUM'
INUMSERVER = 'INUMSERVER'
MSC = 'MSC'
OBGW = 'OBGW'
OMGW = 'OMGW'
PLMN = 'PLMN'
NTHLRFE = 'NTHLRFE'
